---
- name: Update Supervisor
  ansible.builtin.command: supervisorctl reread
  changed_when: true
  notify: Apply Supervisor changes

- name: Apply Supervisor changes
  ansible.builtin.command: supervisorctl update
  changed_when: true
